#----------------------------------
#!/bin/bash
#PBS -q grau
#PBS -S /bin/bash
#PBS -l nodes=1:ppn=8
#PBS -l walltime=12:00:00
#PBS -N xoc
#-----------------------------------------------------------
#                                                                                                                                                      
system=xoc  #esto es el nombre de nuestro fdf y hay que cambiarlo con respecto a lo que tengamos. NO hay que poner el .fdf

echo Running on `hostname`
echo This jobs runs on the following processors:
echo `cat $PBS_NODEFILE`
NSLOTS=`wc -l < $PBS_NODEFILE`
echo This job has allocated $NSLOTS nodes
#
cd $PBS_O_WORKDIR
pwd
date
echo "-----------"

echo " Run SIESTA MD example"

source /home/nicpa/.nicpa_software/nicparc.bash
module load siesta.4.1-b2
prog=siesta
mpirun -np $NSLOTS -hostfile $PBS_NODEFILE $prog <$system.fdf>$system.out
date

killall python
killall siesta
